### PR TITLE
feat: improving state solution

### PR DESCRIPTION
**Pull request by PandasProperty**
Submitted proposal on upwork and here is a video explaining the improvements. As you can see the optimizations are pretty clear https://drive.google.com/file/d/1pm8cg97tU3QVSQVDuC3JTNheGWFiOBi5/view?usp=sharing

First issue was the Context. React Context we use for data that doesn't change a lot, like user language or the theme. Because when the value of the context is updated (what was happening when the was an input) all the elements that were wrapped in the context are rerendered.

After this you can see a small improvement, but still the re-renders of the `ExcelLikeTable` component are two often. So let's send only the part of the global data that interests us, the default values set them from the beginning and move the update logic in the NestedBoard.

The NestedBoard can contain the state of global data, right now it is in the `App`.

### CODE REVIEW

**Comment by cl-en** [comment]
Hi. 
Thanks for the detailed explanation. You did a lot of things great! I really like it. 

But please notice the bottom bar, where the buttons Cancel, Back and Next are located.
The Next button is disabled and becomes enabled only if **at least one row has values for Bar and Quantity**. 
That bar was using context to know when the fields are properly filled.

In your case the Next button does never become enabled.
If your solution can track that as well that would be the final solution.

**Comment by PandasProperty** [comment]
@cl-en I had a typo. Please check the last version. Performance is still there and behaviour as old client. Let me know it other issues

**Comment by PandasProperty** [comment]
Let me know it other behavior does not match :) should be quick fix

**Comment by cl-en** [comment]
Works now great, thanks.

I noticed 2 small things:

1. the Cancel button does not work
2. the fields had a maximum limit of 20000 (if this is too much work to make it work again, ignore this)

Meanwhile, I will proceed to Upwork for payment.
Could you please provide me the price?

**Comment by PandasProperty** [comment]
@cl-en I fixed the Cancel (1)
For (2) are you sure it was working before?

It does not work (it never worked) when typing the number on keyboard only if you press arrow up.
Here is on master: you can input what number you want
 
Screenshot 2024-04-22 at 21 46 12

Look here https://drive.google.com/file/d/1KOSKrZTuLVgB5fNxApl2MDY1nh0jLxiz/view?usp=sharing  it shows that this never worked

Let me do something for you so that will work :D

**Comment by PandasProperty** [comment]
The same if you input -1, it allows you. The validation never worked, tested on main.

**Comment by PandasProperty** [comment]
The fee is 1 hour what I asked for on upwork. (Anda Nenu). You are my first job on upwork. I'm looking at that with the validation and will let you know.

**Comment by cl-en** [comment]
Ok. I've sent you the contract and added a +10$ tip for your great work and to make your first job a sweeter memory :D

**Pull request merged**
